backend:
  name: git-gateway
  branch: main # Asegúrate de que tu rama se llame main (o master)

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - name: "inicio"
        label: "Página de Inicio"
        file: "src/content/inicio.md"
        fields:
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Subtítulo", name: "subtitle", widget: "string"}
          - {label: "Cuerpo", name: "body", widget: "markdown"}
